// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnemrlwarxgnzbqycuoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZW1ybHdhcnhnbnpicXljdW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTYwNjEsImV4cCI6MjA3MDgzMjA2MX0.UvtnGS19-E0xNcZ9x8J19Eie5cwpSQvBG93Ebs_3kng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web',
    },
  },
  // Add retry logic for better connection stability
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
  },
});