// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://benxrhpjitojsfuyjcio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_tD0TaiQNURPwEASOrakUMQ_osLzXW_h";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web',
    },
  },
  // Add retry logic for better connection stability
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
  },
});